[build]
builder = "NIXPACKS"

[deploy]
startCommand = "dotnet RecipeManagementApi.dll --urls http://0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ASPNETCORE_ENVIRONMENT = "Production"
